[package]
name = "string_refcell_comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.9.0"

[[bench]]
name = "string_refcell_comparison"
harness = false
